# Project
mod_version=26.1.0.1
maven_group=com.unrealdinnerbone
mod_name=ObsidianBoat
mod_author=UnRealDinnerbone
mod_id=obsidianboat
curse_id=510648

# Common
minecraft_version=26.1

neo_version=26.1.0.1-beta

fabric_version=0.144.0+26.1
fabric_loader_version=0.18.4

# Other
trenzalore_version=26.1.0.1

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
